### ISSUE TITLE
Upstream rtlamr update to fix unique flag

### ISSUE THREAD

**Issue by apaperclip** [seanauff/metermon#15]
rtlamr was updated to correct the behavior of the unique [flag ](https://github.com/bemasher/rtlamr/issues/193)  

Does the docker hub image build occur at regular intervals or can it be kicked off?

**Comment by seanauff** [comment]
Just built new images and pushed to Dockerhub!

**Comment by apaperclip** [comment]
@seanauff  Thanks for the quick build!

But it is odd, docker hub isn't giving me the new image.   Docker says image updated a few hours ago.

 So I removed the local image, pulled  it again.  My local hash matches docker hub, but the rltamr binary in it is dated 6/6.  Is it possible the new build didnt pull from git? or used a cached build?

**Comment by seanauff** [comment]
Are you on amd64 or arm? I built the arm image myself and purposely didn't use cache, but the amd64 image was built on dockerhub.

**Comment by apaperclip** [comment]
it was the amd64 build.

**Comment by seanauff** [comment]
I just built locally and pushed to the hub!

**Comment by apaperclip** [comment]
There we go! thank you for working through this with me.  Odd dockerhub didn't handle the upstream change, that feels like a pretty normal thing :)
