### ISSUE TITLE
could rtl_tcp be added to this image?

### ISSUE THREAD

**Issue by ponchohoncho** [seanauff/metermon#18]
This could be outside of the scope of this project, but it would be pretty great if this was an all in one container for collecting meter information. Since my SDR device will be dedicated to listening for these sensors, I don't get much out of having it available on rtl_tcp in another container.

**Comment by seanauff** [comment]
That's a tough call if it is in scope or not. On one hand, it would make it more convenient for this specific use case, but it also goes against the point of docker in having each service in a separate container. I think in scope would be an expansion of the instructions and docker compose example to include setting up the rtl_tcp container, and that bundling rtl_tcp would be better suited to a fork.

**Comment by seanauff** [comment]
I added rtl_tcp to the docker compose file.
