### ISSUE TITLE
Cannot view SCM+ messages from my gas meter

### ISSUE THREAD

**Issue by mzeesimba** [seanauff/metermon#19]
Hi,
I am using metermon on HomeAssistant.  I run into an issue whereby I was not getting the messages from my gas meter.  Someone suggested I use the latest build of rtlamr to diagnose messages from my updated gas meter. In trying it out, I run into the following error message. Below is the log of the session from rtlamr:

C:\Users\giveaway\go\bin>rtlamr -msgtype=scm+
14:11:04.032035 decode.go:45: CenterFreq: 912600155
14:11:04.032562 decode.go:46: SampleRate: 2359296
14:11:04.033079 decode.go:47: DataRate: 32768
14:11:04.033595 decode.go:48: ChipLength: 72
14:11:04.034627 decode.go:49: PreambleSymbols: 16
14:11:04.035142 decode.go:50: PreambleLength: 2304
14:11:04.035674 decode.go:51: PacketSymbols: 128
14:11:04.036189 decode.go:52: PacketLength: 18432
14:11:04.036704 decode.go:59: Protocols: scm+
14:11:04.037241 decode.go:60: Preambles: 0001011010100011
14:11:04.041858 main.go:124: GainCount: 29
{Time:2021-11-24T14:11:05.954 SCM+:{ProtocolID:0x1E EndpointType:0x9C EndpointID: 75387939 Consumption: 12216 Tamper:0x0100 PacketCRC:0xF3B5}}
{Time:2021-11-24T14:11:20.953 SCM+:{ProtocolID:0x1E EndpointType:0x9C EndpointID: 75387939 Consumption: 12216 Tamper:0x0100 PacketCRC:0xF3B5}}
{Time:2021-11-24T14:12:06.454 SCM+:{ProtocolID:0x1E EndpointType:0x9C EndpointID: 75387939 Consumption: 12216 Tamper:0x0100 PacketCRC:0xF3B5}}
14:12:13.843551 main.go:343: Receiver context cancelled.
14:12:13.844253 main.go:320: read tcp 127.0.0.1:61773->127.0.0.1🔢 i/o timeout
io.ReadFull
main.(*Receiver).Run.func2
C:/Users/giveaway/go/pkg/mod/github.com/bemasher/rtlamr@v0.9.3/main.go:181
runtime.goexit
C:/Program Files/Go/src/runtime/asm_amd64.s:1581

So I actually can get the reading from my meter (75387939) however I am not able to see the meter from metermon messages. I see several nearby meters (both gas and electric) but I cannot seem to get my meter.

Any pointers on why I cannot see my specific meter from metermon?  
Meter Spec: https://www.itron.com/-/media/feature/products/documents/spec-sheet/100g-dls-spec-sheet.pdf

Thanks

**Comment by seanauff** [comment]
I'm guessing your PR fixed the issue?

**Comment by mzeesimba** [comment]
Yes it did. Thank you!

**Comment by seanauff** [comment]
glad to hear it!
