### ISSUE TITLE
Unable to see my meter?

### ISSUE THREAD

**Issue by enkrypt3d** [seanauff/metermon#21]
{"Protocol": "SCM", "Type": "Gas", "ID": "12292023", "Consumption": 268918, "Unit": "ft^3"}
{"Protocol": "R900", "Type": "Water", "ID": "700975996", "Consumption": 30816.7, "Unit": "gal"}
{"Protocol": "SCM", "Type": "Gas", "ID": "46037303", "Consumption": 940418, "Unit": "ft^3"}
{"Protocol": "SCM", "Type": "Gas", "ID": "12292023", "Consumption": 268923, "Unit": "ft^3"}
{"Protocol": "R900", "Type": "Water", "ID": "700975996", "Consumption": 30817.9, "Unit": "gal"}

I can see everyone's but mine.... my meter is a honeywell AC-250 which runs on 900Mhz. Is there a way to change the frequency metermon listens on?

**Comment by seanauff** [comment]
I would check over on rtlamr (https://github.com/bemasher/rtlamr) if that specific meter is supported and try running rtlamr standalone to see if you can get readings out of your meter. If so, then I can investigate why metermon is not picking it up.

**Comment by enkrypt3d** [comment]
> I would check over on rtlamr (https://github.com/bemasher/rtlamr) if that specific meter is supported and try running rtlamr standalone to see if you can get readings out of your meter. If so, then I can investigate why metermon is not picking it up.

Thanks - got rtlamr collecting so we'll see. The gas meter is a Itron B172 FYI. I could not find it on your compatibility list :(

**Comment by enkrypt3d** [comment]
same issue - is there a way to change the frequency?

**Comment by enkrypt3d** [comment]
it looks like my meter is a SCM+. Does metermon support SCM+ protocol?

**Comment by enkrypt3d** [comment]
Here is my meter with SCM+ enabled on RTLAMR:
{Time:2021-12-01T16:14:47.989 SCM+:{ProtocolID:0x1E EndpointType:0x9C EndpointID:  ######## Consumption:       212 Tamper:0x0B08 PacketCRC:0x46BF}}

Here's a snip of the output with running: rtlamr -msgtype=scm,scm+

Let me know what options to use when launching your docker and I can test it. Thanks for your help!

**Comment by seanauff** [comment]
are you using the latest docker image? there was a PR (#20) submitted within the past week to add that EndpointType (0c9C = 156) to the list of gas meters that metermon listens to.

**Comment by enkrypt3d** [comment]
I was able to update the docker image and now I can see the SCM+ messages. Thank you!! we can close this issue.

**Comment by seanauff** [comment]
glad it works!
