### ISSUE TITLE
docker wont "run" the application...

### ISSUE THREAD

**Issue by gbdavidx** [seanauff/metermon#28]
I installed docker on my raspberry pi zero, but when i run it, i keep getting a warning meesage, 
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm/v6) and no specific platform was requested
when i do docker container ls, nothing shows up...

pi@raspberrypi:~/metermon $ docker version
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:29 2022
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:31 2022
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

When i try to download it again, i get
arm: Pulling from seanauff/metermon
Digest: sha256:9665ac4aae0694a453c13d1e6b4e5af47e8a12c1d31decf1d2aa283c1ba612f6
Status: Image is up to date for seanauff/metermon:arm
docker.io/seanauff/metermon:arm

**Comment by gbdavidx** [comment]
seems like there might be a tag needed for pi zero, similar issue https://github.com/node-red/node-red-docker/issues/150

**Comment by seanauff** [comment]
I believe this is due to not having a pre-built image for armv6. Since I don't have an Pi Zero (and haven't figured out how to build multi-arch images), you'll need to build the image yourself on your Pi Zero using the instruction in the readme.
