### ISSUE TITLE
High CPU usage on RTLAMR

### ISSUE THREAD

**Issue by enkrypt3d** [seanauff/metermon#33]
RTLAMR is using 110% of the CPU... please advise

**Comment by seanauff** [comment]
What hardware is this running on? Does rtlamr behave the same when running standalone?

**Comment by enkrypt3d** [comment]
It's running on a raspberry pi 4 with 8gb memory and the latest raspian. I
have not tried it elsewhere.

**Comment by seanauff** [comment]
In that case it may just be a quirk of the monitoring software you are using - see here: [https://forums.raspberrypi.com/viewtopic.php?t=215814](https://forums.raspberrypi.com/viewtopic.php?t=215814)

**Comment by enkrypt3d** [comment]
Any ideas how to throttle this process? It's causing issues with other things running on this pi 4......

**Comment by seanauff** [comment]
rtlamr can be quite CPU intensive, especially if decoding multiple protocols simultaneously (see [here](https://github.com/bemasher/rtlamr/wiki/Multi-Protocol-Decoding)). What are you using for `RTLAMR_MSGTYPE`?

**Comment by enkrypt3d** [comment]
Using SCM+ to get my meter info. I'm working on moving home assistant to a
much more powerful system running unraid. I just need to figure out how to
setup your docker image on unraid and have it talk to the HA OS VM on the
same machine....
