### ISSUE TITLE
No Metermon Topics Shown for HASS MQTT

### ISSUE THREAD

**Issue by M3Power95** [seanauff/metermon#35]
Hello,

I am new to working with GitHub and HA, so not sure if this is the right place to put this, so I apologize in advance if this isn't the appropriate forum for this post. 

Got the metermon docker container set up on my RPi and planning on using it to send to my Mosquitto broker add-on in Home Assistant. My setup runs HAOS as a Linux VM in Proxmox, and Mosquitto is running as an add-on in there. I was able to get the container running on the Pi, but I am not seeing any Metermon topics show up in MQTT Explorer. The docker start command I ran was:

docker run -d -e MQTT_BROKER_HOST=My_HAOS_vm_ip -e MQTT_USERNAME=My_HAOS_Username -e MQTT_PASSWORD=My_HAOS_PW -e RTL_TCP_SERVER=My_rPi_IP:1234 seanauff/metermon:arm

Initially got an error in the terminal that the password event was not recognized. The password starts and ends with a number, and the error response in the terminal cut off the first number of my password in its response, so maybe this is where my issue is. Next I tried to eliminate MQTT_USERNAME and MQTT_PASSWORD environment variables in the container run command to this:

docker run -d -e MQTT_BROKER_HOST=My_HAOS_vm_ip -e RTL_TCP_SERVER=My_rPi_IP:1234 seanauff/metermon:arm

The container started but I am not seeing it when I start MQTT Explorer in HAOS. Any recommendations on what I'm missing?

**Comment by seanauff** [comment]
can you provide the terminal output of the metermon container when it starts?

**Comment by M3Power95** [comment]
> can you provide the terminal output of the metermon container when it starts?

Attached are screenshots of the terminal after a few attempts to get the docker running, and then my MQTT explorer not showing metermon. Thanks for your help
![20240617_205625](https://github.com/seanauff/metermon/assets/166347006/5a8b70a6-1b0a-4cdf-93a0-fd01c04b76b4)
![MQTT Explorer](https://github.com/seanauff/metermon/assets/166347006/2c7f5ca6-6069-4221-8f14-d21242b37c69)

**Comment by M3Power95** [comment]
Left one detail here that may matter just to clarify. The Proxmox server that runs the Home Assistant VM where my Mosquitto broker Add-on is running, is a separate piece of hardware, an Intel NUC. The RPi running the metermon docker is an older bare metal RPi 3B+ running Raspbian.

**Comment by seanauff** [comment]
can you restart the container and then get the logs via
`docker logs <container ID>`

**Comment by M3Power95** [comment]
Looks like a lot of refused connections to the broker due to "Not authorized." Which doesn't surprise me considering it wouldn't accept my username and password for HA. Any idea why that is? It's like the docker response truncates the first number off my password for some reason.

![20240618_223153](https://github.com/seanauff/metermon/assets/166347006/1524a9bd-0ae5-4125-88a7-e6198f4b9b05)

**Comment by seanauff** [comment]
Definitely seems like an issue getting your password into the docker run command. Does your password have special characters? you make have to try different versions of quotes surrounding it.

**Comment by M3Power95** [comment]
It does have special characters in it. Specifically, it looks like 1!****!1. I tried single quotes "", but not double quotes. I will try that. If that does not work, is the only solution to change the password to not include special characters?

**Comment by M3Power95** [comment]
So no matter what I tried, I couldn't get it to work. Figured that somehow the docker response was truncating the special characters on my HA login, so I changed it to a format that started with a letter, and that worked! I can see the metermon topics in my HA instance in MQTT Explorer now. Thanks!

**Comment by M3Power95** [comment]
So no matter what I tried, I couldn't get it to work. Figured that somehow the docker response was truncating the special characters on my HA login, so I changed it to a format that started with a letter, and that worked! I can see the metermon topics in my HA instance in MQTT Explorer now. Thanks!

**Comment by seanauff** [comment]
Glad it is working!
