### ISSUE TITLE
Endpoint Type no longer recognized

### ISSUE THREAD

**Issue by yanky79** [seanauff/metermon#39]
I had to rebuild my image that collected the Meter data and for some reason I am no longer getting data for the water meter.,  When I run rtlamr with the msgtype=all It picks up the meter with this output

`{Time:2024-07-11T23:21:27.345 SCM+:{ProtocolID:0x1E EndpointType:0x1B EndpointID: 120601349 Consumption:   1255268 Tamper:0x2500 PacketCRC:0xE0F6}}`

I think it has to do with this endpoint type - `0x1B`, since `0x9C `and `0xAB `are both visible in MeterMon

I have tried to start the docker with the RTLAMR_MSGTYPE=all switch, but that did not change the output

**Comment by yanky79** [comment]
I meant to add that this is running on a Rpi4 using Ubuntu 24.04 LTS (Noble Numbat), with rtl_tcp in a docker container too.

**Comment by seanauff** [comment]
0x1B (27) wasn't in the list before, so it shouldn't have been showing up. But I just added it: https://github.com/seanauff/metermon/commit/4b1a7640075d6ab486a9b5f767fde477defc98f5

I build new images and pushed them to dockerhub, go ahead and give it a try.

**Comment by yanky79** [comment]
Confirmed, it is now picking it up - thanks
