### ISSUE TITLE
Add a flag for unit division

### ISSUE THREAD

**Issue by michaelwoods** [seanauff/metermon#6]
My water meter seems to be reporting the correct number of gallons when comparing to my bill. However the value is divided by `10.0` resulting in hundreds of gal / month rather than thousands.

Adding either a flag or custom multiplier would help solve this issue.

**Comment by seanauff** [comment]
Hi, I just added this ability! I haven't actually tested it though, so let me know if it works.

**Comment by michaelwoods** [comment]
Thanks! Though it looks like we need a simple `float()` conversion. PR'ed: #12 

```
TypeError: unsupported operand type(s) for /: 'int' and 'str'
```

**Comment by seanauff** [comment]
Merged your PR, let me know how it goes now!

**Comment by michaelwoods** [comment]
Working as expected, thanks for your work on this project :+1:
